//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRABAJO_CRUDF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HN3C64M\\SQLEXPRESS;Initial Catalog=Trabajo_Crud;Integrated Se" +
            "curity=True;TrustServerCertificate=True")]
        public string Trabajo_CrudConnectionString {
            get {
                return ((string)(this["Trabajo_CrudConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=L301-18\\SQLEXPRESS;Initial Catalog=Trabajo_Crud;Integrated Security=T" +
            "rue;TrustServerCertificate=True")]
        public string Trabajo_CrudConnectionStringf {
            get {
                return ((string)(this["Trabajo_CrudConnectionStringf"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=L301-19\\SQLEXPRESS;Initial Catalog=Trabajo_Crud;Integrated Security=T" +
            "rue;TrustServerCertificate=True")]
        public string Trabajo_CrudConnectionStringclase {
            get {
                return ((string)(this["Trabajo_CrudConnectionStringclase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1Q8OQ78\\SQLEXPRESS;Initial Catalog=Trabajo_Crud;Integrated Se" +
            "curity=True;TrustServerCertificate=True")]
        public string Trabajo_CrudConnectionStringMARTES {
            get {
                return ((string)(this["Trabajo_CrudConnectionStringMARTES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44328/MIWSPERUCA.asmx")]
        public string TRABAJO_CRUDF_AlumnosYAsignaturasWS_MIWSPERUCA {
            get {
                return ((string)(this["TRABAJO_CRUDF_AlumnosYAsignaturasWS_MIWSPERUCA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=L301-17\\SQLEXPRESS;Initial Catalog=Trabajo_Crud;Integrated Security=T" +
            "rue;TrustServerCertificate=True")]
        public string Trabajo_CrudConnectionString1 {
            get {
                return ((string)(this["Trabajo_CrudConnectionString1"]));
            }
        }
    }
}
