USE [master]
GO

/****** Object:  Database [Trabajo_Crud]    Script Date: 10/31/2024 3:55:09 p. m. ******/
CREATE DATABASE [Trabajo_Crud]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Trabajo_Crud', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Trabajo_Crud.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Trabajo_Crud_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Trabajo_Crud_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Trabajo_Crud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Trabajo_Crud] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET ARITHABORT OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Trabajo_Crud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Trabajo_Crud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Trabajo_Crud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Trabajo_Crud] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Trabajo_Crud] SET  MULTI_USER 
GO

ALTER DATABASE [Trabajo_Crud] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Trabajo_Crud] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Trabajo_Crud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Trabajo_Crud] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Trabajo_Crud] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Trabajo_Crud] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Trabajo_Crud] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Trabajo_Crud] SET  READ_WRITE 
GO

